set nocompatible

syntax enable
filetype plugin indent on

set backspace=indent,eol,start
set expandtab ts=4 sw=4
set ignorecase incsearch
set mouse=a
set noswapfile undofile
set scrolloff=5
set wildmenu

call plug#begin()
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'jiangmiao/auto-pairs'
    Plug 'lervag/vimtex'
    Plug 'mbbill/undotree'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'tpope/vim-commentary'
    Plug 'tpope/vim-fugitive'
call plug#end()

let g:ctrlp_map = '<c-p>'
let g:vimtex_view_general_viewer = 'texworks.exe'
let target_path = expand('~/.undodir')
if !isdirectory(target_path)
	call mkdir(target_path, "p", 0700)
endif
let &undodir=target_path

set termguicolors
colorscheme habamax
highlight EndOfBuffer guibg=NONE ctermbg=NONE
highlight Normal guibg=NONE ctermbg=NONE
highlight Terminal guibg=NONE ctermbg=NONE
highlight ModeMsg ctermbg=NONE ctermfg=107 guibg=NONE guifg=#95B47B
highlight VertSplit guibg=NONE ctermbg=NONE
let g:netrw_banner=0

nnoremap <silent>   <C-n> :set nonu! nornu!<CR>
nnoremap <silent>   <tab> :bnext<CR>
nnoremap <silent> <s-tab> :bprevious<CR>
autocmd InsertEnter * if &number | set nornu | endif
autocmd InsertLeave * if &number | set rnu | endif
autocmd WinEnter * if &number | set rnu | endif
autocmd WinLeave * if &number | set nornu | endif
autocmd WinEnter * if &colorcolumn==0 | set colorcolumn=81 | endif
autocmd WinLeave * if &colorcolumn==81 | set colorcolumn=0 | endif
